"""theme.json generator and SVG skeleton composer."""
import json
from pathlib import Path


SKELETON_TEMPLATE = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="-15 -25 45 45" shape-rendering="crispEdges">
  <defs>
    {defs}
  </defs>
  <style>
    #sprite-anim {{
      transform-origin: {origin_x}px {origin_y}px;
      animation: {sprite_keyframe} {sprite_duration} ease-in-out infinite;
    }}
    {style_extras}
  </style>

  <g id="body-js">
    <g id="overlay-back">{overlay_back}</g>
    <g id="sprite-vec">
      <g id="sprite-anim">
        <g id="sprite-content">
      {sprite_rects}
        </g>
      </g>
      {tint}
    </g>
    {eyes_js}
    <g id="overlay-front">{overlay_front}</g>
  </g>

  <g id="shadow-js">
    <ellipse cx="7.5" cy="16.5" rx="6" ry="0.5" fill="#000" opacity="0.2"/>
  </g>
</svg>
"""


# Per-state animation: (keyframe name, duration). Kept inside the sprite so
# Chromium-under-<object> renders it (clawd convention: CSS in SVG <style>).
STATE_ANIMS = {
    "idle": ("breathe", "1.6s"),
    "thinking": ("think-sway", "2.2s"),
    "working": ("bounce", "0.4s"),
    "error": ("shake", "0.18s"),
    "attention": ("jump", "0.5s"),
    "notification": ("pulse", "0.8s"),
    "sleeping": ("sleep-breathe", "3.2s"),
    "waking": ("stretch", "1.4s"),
}

KEYFRAMES = {
    "breathe": """
    @keyframes breathe {
      0%, 100% { transform: translateY(0); }
      50%      { transform: translateY(-0.3px); }
    }
    """,
    "think-sway": """
    @keyframes think-sway {
      0%, 100% { transform: rotate(0deg) translateY(0); }
      25%      { transform: rotate(-2deg) translateY(-0.4px); }
      75%      { transform: rotate(2deg) translateY(-0.4px); }
    }
    """,
    "bounce": """
    @keyframes bounce {
      0%, 100% { transform: translateY(0); }
      50%      { transform: translateY(-0.8px); }
    }
    """,
    "shake": """
    @keyframes shake {
      0%, 100% { transform: translateX(0); }
      25%      { transform: translateX(-0.6px); }
      75%      { transform: translateX(0.6px); }
    }
    """,
    "jump": """
    @keyframes jump {
      0%, 100% { transform: translateY(0); }
      30%      { transform: translateY(-1.2px); }
      55%      { transform: translateY(0); }
    }
    """,
    "pulse": """
    @keyframes pulse {
      0%, 100% { transform: scale(1); }
      50%      { transform: scale(1.04, 0.98); }
    }
    """,
    "sleep-breathe": """
    @keyframes sleep-breathe {
      0%, 100% { transform: translateY(0.2px) scale(1, 1); }
      50%      { transform: translateY(0.2px) scale(1.03, 0.96); }
    }
    """,
    "stretch": """
    @keyframes stretch {
      0%, 100% { transform: scale(1, 1); }
      50%      { transform: scale(0.94, 1.08); }
    }
    """,
}


def state_svg(
    state: str,
    sprite_rects_xml: str,
    eyes_js_block: str,
    origin_cx: float = 7.5,
    origin_cy: float = 7.0,
) -> str:
    """Compose one state SVG: sprite + eyes + per-state animation."""
    keyframe, duration = STATE_ANIMS[state]
    return SKELETON_TEMPLATE.format(
        defs="",
        origin_x=f"{origin_cx:.2f}",
        origin_y=f"{origin_cy:.2f}",
        sprite_keyframe=keyframe,
        sprite_duration=duration,
        style_extras=KEYFRAMES[keyframe],
        overlay_back="",
        sprite_rects=sprite_rects_xml,
        tint="",
        eyes_js=eyes_js_block,
        overlay_front="",
    )


def theme_json(
    theme_id: str,
    display_name: str,
    state_map: dict[str, str],
    eye_tracking_states: list[str],
    content_w: float = 23.0,
    content_h: float = 20.0,
) -> dict:
    """Build theme.json dict.

    content_w/h is the visible body box in viewBox units, aspect-matched to
    the source sprite so clawd's normalized layout renders it undistorted.
    eye_tracking_states: SVG states carrying #eyes-js (empty for APNG themes).
    """
    ox = -4.0 + (23.0 - content_w) / 2  # center box horizontally
    eye_tracking = {"enabled": False} if not eye_tracking_states else {
        "enabled": True,
        "states": eye_tracking_states,
        "maxOffset": 0.5,
        "ids": {
            "eyes": "eyes-js",
            "body": "body-js",
            "shadow": "shadow-js",
        },
    }
    return {
        "schemaVersion": 1,
        "id": theme_id,
        "name": display_name,
        "version": "0.1.0",
        "description": f"Theme generated by whistle for {display_name}",
        "license": "Personal use",
        "viewBox": {"x": -15, "y": -25, "width": 45, "height": 45},
        "layout": {
            "contentBox": {"x": ox, "y": -3, "width": content_w, "height": content_h},
            "centerX": ox + content_w / 2,
            "baselineY": -3 + content_h,
            "visibleHeightRatio": 0.58,
            "baselineBottomRatio": 0.05,
        },
        "eyeTracking": eye_tracking,
        "states": {k: [v] for k, v in state_map.items()},
        # ponytail: direct sleep sequence — whistle ships 8 states only;
        # full mode would require yawning/dozing/collapsing states.
        "sleepSequence": {"mode": "direct"},
        "hitBoxes": {
            "default": {"x": -1, "y": 5, "w": 17, "h": 12},
            "sleeping": {"x": -1, "y": 5, "w": 17, "h": 12},
        },
        "miniMode": {"supported": False},
        "objectScale": {
            "widthRatio": 1.9,
            "heightRatio": 1.3,
            "offsetX": -0.45,
            "offsetY": -0.25,
        },
    }


def write_theme(
    out_dir: Path,
    theme_id: str,
    name: str,
    svg_files: dict[str, str | bytes],
    eye_states: list[str] | None = None,
    content_w: float = 23.0,
    content_h: float = 20.0,
) -> None:
    """Write theme.json + assets/* to out_dir/theme_id/.

    str values are written as .svg, bytes as .apng (frame-animated states).
    eye_states: which states carry #eyes-js (SVG only); defaults to all SVGs.
    """
    target = out_dir / theme_id
    (target / "assets").mkdir(parents=True, exist_ok=True)
    state_map = {}
    for state, data in svg_files.items():
        ext = "svg" if isinstance(data, str) else "apng"
        fname = f"{state}.{ext}"
        target_path = target / "assets" / fname
        if isinstance(data, bytes):
            target_path.write_bytes(data)
        else:
            target_path.write_text(data, encoding="utf-8")
        state_map[state] = fname
    if eye_states is None:
        eye_states = [s for s, d in svg_files.items() if isinstance(d, str)]
    tj = theme_json(theme_id, name, state_map, eye_states, content_w, content_h)
    (target / "theme.json").write_text(json.dumps(tj, indent=2), encoding="utf-8")
