"""theme.json generator and SVG skeleton composer."""
import json
from pathlib import Path


SKELETON_TEMPLATE = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="-15 -25 45 45" shape-rendering="crispEdges">
  <defs>
    {defs}
  </defs>
  <style>
    #sprite-anim {{ animation: {sprite_keyframe} {sprite_duration} ease-in-out infinite; }}
    {style_extras}
  </style>

  <g id="body-js">
    <g id="overlay-back">{overlay_back}</g>
    <g id="sprite-vec">
      <g id="sprite-anim">
        <g id="sprite-content">
      {sprite_rects}
        </g>
      </g>
      {tint}
    </g>
    {eyes_js}
    <g id="overlay-front">{overlay_front}</g>
  </g>

  <g id="shadow-js">
    <ellipse cx="7.5" cy="16.5" rx="6" ry="0.5" fill="#000" opacity="0.2"/>
  </g>
</svg>
"""


IDLE_KEYFRAME = """
    @keyframes breathe {
      0%, 100% { transform: translateY(0); }
      50%      { transform: translateY(-0.3px); }
    }
""".strip()


def idle_svg(sprite_rects_xml: str, eyes_js_block: str) -> str:
    return SKELETON_TEMPLATE.format(
        defs="",
        sprite_keyframe="breathe",
        sprite_duration="1.6s",
        style_extras=IDLE_KEYFRAME,
        overlay_back="",
        sprite_rects=sprite_rects_xml,
        tint="",
        eyes_js=eyes_js_block,
        overlay_front="",
    )


def theme_json(
    theme_id: str,
    display_name: str,
    state_map: dict[str, str],
    eye_tracking_states: list[str],
) -> dict:
    """Build theme.json dict."""
    return {
        "schemaVersion": 1,
        "id": theme_id,
        "name": display_name,
        "version": "0.1.0",
        "description": f"Theme generated by whistle for {display_name}",
        "license": "Personal use",
        "viewBox": {"x": -15, "y": -25, "width": 45, "height": 45},
        "layout": {
            "contentBox": {"x": -4, "y": -3, "width": 23, "height": 20},
            "centerX": 7.5,
            "baselineY": 17,
            "visibleHeightRatio": 0.58,
            "baselineBottomRatio": 0.05,
        },
        "eyeTracking": {
            "enabled": True,
            "states": eye_tracking_states,
            "maxOffset": 0.5,
            "ids": {
                "eyes": "eyes-js",
                "body": "body-js",
                "shadow": "shadow-js",
            },
        },
        "states": {k: [v] for k, v in state_map.items()},
        "hitBoxes": {
            "default": {"x": -1, "y": 5, "w": 17, "h": 12},
            "sleeping": {"x": -1, "y": 5, "w": 17, "h": 12},
        },
        "miniMode": {"supported": False},
        "objectScale": {
            "widthRatio": 1.9,
            "heightRatio": 1.3,
            "offsetX": -0.45,
            "offsetY": -0.25,
        },
    }


def write_theme(out_dir: Path, theme_id: str, name: str, svg_files: dict[str, str]) -> None:
    """Write theme.json + assets/*.svg to out_dir/theme_id/."""
    target = out_dir / theme_id
    (target / "assets").mkdir(parents=True, exist_ok=True)
    state_map = {}
    for state, svg_text in svg_files.items():
        fname = f"{state}.svg"
        (target / "assets" / fname).write_text(svg_text, encoding="utf-8")
        state_map[state] = fname
    tj = theme_json(theme_id, name, state_map, list(svg_files.keys()))
    (target / "theme.json").write_text(json.dumps(tj, indent=2), encoding="utf-8")
